KuonPacketCapture: main.c endian_operations.c utils.c
	mips-openwrt-linux-gcc -L/home/michael/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -lpcap -o KuonPacketCapture main.c endian_operations.c utils.c
